name: Build Keyball44 Custom Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup QMK
        uses: qmk/setup-qmk@v1

      - name: Install required python dependencies
        run: python3 -m pip install -r __qmk__/requirements.txt

      - name: Compile
        run: qmk compile -kb keyball/keyball44 -km sam_custom

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: keyball44_sam_custom
          path: |
            *.hex
            *.bin
            *.uf2
